stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE: "mydockerhubuser/myapp:latest"

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
    - docker build -t $DOCKER_IMAGE .
    - docker push $DOCKER_IMAGE
  only:
    - main

deploy:
  stage: deploy
  image: appleboy/ssh-action
  script:
    - ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "cd ~/app && docker-compose pull && docker-compose up -d"
  only:
    - main
