stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE: "mydockerhubuser/myapp:latest"

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  script:
    - docker build -t $DOCKER_IMAGE .
    - docker push $DOCKER_IMAGE

deploy:
  stage: deploy
  image: appleboy/drone-ssh:latest
  script:
    - ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "cd /home/user/app && docker-compose pull && docker-compose up -d"
